disk claims and tentative new entrypoint for agent

diff --git a/kubernetes-manifests/rl-agent/app/agent.yaml b/kubernetes-manifests/rl-agent/app/agent.yaml
--- a/kubernetes-manifests/rl-agent/app/agent.yaml
+++ b/kubernetes-manifests/rl-agent/app/agent.yaml
@@ -33,6 +33,22 @@ spec:
             echo "Error: Could not reach Prometheus API"
             exit 1
           fi
+      - name: kubernetes-check
+        image: curlimages/curl:latest
+        command:
+        - /bin/sh
+        - -c
+        - |
+        echo "Checking Kubernetes API..."
+        if ! curl -sf http://prometheus.istio-system.svc.cluster.local:9090; then
+          echo "Error: Could not reach Kubernetes API"
+          exit 1
+        fi
+
+        volumeMounts:
+          - name: ca-cert
+            mountPath: /secrets
+
       containers:
       - name: server
         image: gcr.io/master-thesis-hpa/agent:0.3.1
@@ -62,3 +78,6 @@ spec:
         - name: file-storage
           persistentVolumeClaim:
             claimName: nfs-server-claim
+        - name: ca-cert
+            secret:
+              secretName: # create one
